pizza_shop/config/routes.rb
Rails.application.routes.draw do
  root 'pizzas#home'
  get 'about' => 'pizzas#about'
  resources :pizzas

end

pizza_shop/app/models/pizza.rb
class Pizza < ActiveRecord::Base
end

pizza_shop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

pizza_shop/app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  before_action :set_pizza, only: [:show, :edit, :update, :destroy]

  # GET /pizzas
  # GET /pizzas.json

  def home

  end

  def about

  end

  def index
    @pizzas = Pizza.all
  end

  # GET /pizzas/1
  # GET /pizzas/1.json
  def show
  end

  # GET /pizzas/new
  def new
    @pizza = Pizza.new
  end

  # GET /pizzas/1/edit
  def edit
  end

  # POST /pizzas
  # POST /pizzas.json
  def create
    @pizza = Pizza.new(pizza_params)

    respond_to do |format|
      if @pizza.save
        format.html { redirect_to @pizza, notice: 'Pizza was successfully created.' }
        format.json { render :show, status: :created, location: @pizza }
      else
        format.html { render :new }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pizzas/1
  # PATCH/PUT /pizzas/1.json
  def update
    respond_to do |format|
      if @pizza.update(pizza_params)
        format.html { redirect_to @pizza, notice: 'Pizza was successfully updated.' }
        format.json { render :show, status: :ok, location: @pizza }
      else
        format.html { render :edit }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizzas/1
  # DELETE /pizzas/1.json
  def destroy
    @pizza.destroy
    respond_to do |format|
      format.html { redirect_to pizzas_url, notice: 'Pizza was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pizza
      @pizza = Pizza.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pizza_params
      params.require(:pizza).permit(:name, :crust, :sauce, :toppings, :cost, :image)
    end
end

pizza_shop/app/helpers/application_helper.rb
module ApplicationHelper
end

pizza_shop/app/helpers/pizzas_helper.rb
module PizzasHelper
end

pizza_shop/app/views/pizzas/_form.html.erb
<%= form_for(@pizza) do |f| %>
  <% if @pizza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pizza.errors.count, "error") %> prohibited this pizza from being saved:</h2>

      <ul>
      <% @pizza.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :crust %><br>
    <%= f.text_field :crust %>
  </div>
  <div class="field">
    <%= f.label :sauce %><br>
    <%= f.text_field :sauce %>
  </div>
  <div class="field">
    <%= f.label :toppings %><br>
    <%= f.text_area :toppings %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.number_field :cost %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

pizza_shop/app/views/pizzas/about.html.erb
<h1>About me</h1>

<ul>
	<li>Cool</li>
	<li>Been doing this for 50 years</li>
</ul>

pizza_shop/app/views/pizzas/edit.html.erb
<h1>Editing Pizza</h1>

<%= render 'form' %>

<%= link_to 'Show', @pizza %> |
<%= link_to 'Back', pizzas_path %>

pizza_shop/app/views/pizzas/home.html.erb
<div class="jumbotron">
	<center>
		<h1>Welcome to my Pizza Shack!</h1>
		<img src="https://197c2b2de2695f3fc516-9d1369894b0466c92e9c5ccf435da7e6.ssl.cf3.rackcdn.com/2053/img/gallery/2015-05-19_pizza.jpg" alt="">
		<%= link_to 'Check out our Pizzas!', pizzas_path, class: "btn btn-default" %>
	</center>
</div>

pizza_shop/app/views/pizzas/index.html.erb
<h1>All of our Pizzas</h1>
<div class="row">
  <% @pizzas.each do|pizza| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img src="<%= pizza.image %>" alt="">
        <div class="caption">
          <h3> <%= pizza.name %></h3>
          <h3>Cost $<%= pizza.cost %></h3>
          <%= link_to 'More Info', pizza, class: "btn btn-default" %>
        </div>
      </div>
    </div>
    <% end %>
</div>

<%= link_to 'New Pizza', new_pizza_path %>

pizza_shop/app/views/pizzas/new.html.erb
<h1>New Pizza</h1>

<%= render 'form' %>

<%= link_to 'Back', pizzas_path %>

pizza_shop/app/views/pizzas/show.html.erb
<div class="jumbotron">
  <center>
    <h1><%= @pizza.name %></h1>
    <img src="<%= @pizza.image %>" alt="">
  </center>
  <h3>Crust: <%= @pizza.crust %></h3>
  <h3>Sauce: <%= @pizza.sauce %></h3>
  <h3>Toppings: <%= @pizza.toppings %></h3>
  <h3>Cost: <%= @pizza.cost %></h3>
</div>

<%= link_to 'Edit', edit_pizza_path(@pizza) %> |
<%= link_to 'Back', pizzas_path %>